{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7c722758-e97b-48c9-a3f5-9f4c63ac3725",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_31.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/ee3e2d535baeff1cca272e639f4b62df-e62e76091a612927e8cdc117bedfcfff:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_31.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_24.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/7f357e1ba94edb70dc10dd10de6322d2-f04763601342e70592fb723dca838623:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_24.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_01.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/cddcc6416d7e9757d3ef618210657ff4-59d3188cb85da1eb9653051c63f131e9:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_01.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_25.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/7f42db6396a52687f933cb2ce7b52599-f5fa80c1523a897e18e932f47cd569ef:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_25.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_02.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/f4a4cc896ddd57b0a605847b888e2908-d8541f945f23c0ce47880bb4c671283c:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_02.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_26.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/9760bcd15c0df36b884ab6969eb8ba52-0affb62d225f7842788426509d66dfe9:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_26.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_03.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/7043970a80651481d37d5ca4784b0109-9c8576d8d991d574a44dd6b917898840:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_03.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_27.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/3aa1353a6baa72240b4716e1c55823cd-eea56698b771f9ed256e48abd4b8963b:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_27.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_04.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a36a9ec1e8a9c75e31205a44794ba3bd-1c44742ea5443101e65ff22da5135f68:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_04.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_28.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/53db253d97936a06659ac7eddeaa3f39-6ab57543737bbd14c468ff46f20f39b2:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_28.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_05.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/243d54ee3fdafabb893ec37126adbd8d-85bf58727343b39a04d27b27680384b8:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_08_05.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_29.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/e6bf65965bce4a3b7daf19eb37e780af-6d13bc9e31493290280675d72152552a:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/2009_07_29.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/d5373835922f390345f7bb33b1866d6c-4bce1f6ea94d5e21e64c7e5f4c81ede3:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2065/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_04.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/2da67daf04d488239d27c41b305e7ddb-7c55c6e6de52b28f6d206c1b24e0afa3:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_04.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_02_25.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/4a20a3dfef841786426a1b088d50a543-a68ac5d0e575013f6a3f71719c9d80fe:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_02_25.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_05.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/8503f36fdf8945a20ce53d62219c5b6e-f83eb1cfabd9266350555704800c4b05:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_05.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_02_26.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/ecca28a550517c85236a8d96ae256715-74ee9dc20df7fb832d41972613d0c2d7:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_02_26.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_06.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/4c28ad055e6825aa9abe2798c0f6210b-e4597f5a6750915fe98d9878839ca198:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_06.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_02_27.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/0d17cf668f4cc03d0fc175d5736a99ea-54a20d15cb8e3daa3b29d30ca521031c:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_02_27.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_07.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/66aa6371c84c15e77ea4d03c14a82dce-2dc568a545c278f502330fed9c002f94:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_07.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_02_28.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/f0e5a75b5d26bd89421206ddca884b3e-393e0558a1aee3d1d11147af2e5db7a9:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_02_28.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_08.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/12019bd11229984a7b29f68c40196976-e296702c9c85c53f5763974d96b10006:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_08.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_01.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/73b37d3aab4352e2b16d30ea2fae5933-54cd1c9d526a07ba786bb493c8cbe31f:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_01.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_09.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/cae58988baa744506557493532f15db5-711b26fb621a4081c79c0d74ed0ef5f7:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_09.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_02.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/acb2c077752ac51877035ad9d3b0df17-ec227c9bdea15f4f1cd79035754aac91:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_02.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_10.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/0158c1fbbfecb85bd1698714e5e89f01-3cf4054981c8aca888198be75c7f4c61:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_10.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_03.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/36f995bcf0d4f3830e0d2f084e2f9330-cdeb2b5c4d9add43b22b2f9e79b2455e:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/2010_03_03.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/e73070c1f5ed953347645ce31097a71d-ef2dd1ae74d074f9a50d6e732571c165:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2096/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_03.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/b8f2472d64dc2cb8542aaf71ff12c596-9b397d72395c5f7b5da549a33987ca8a:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_03.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_05_27.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a1beff4dfe251626ff420b0c158aa442-b018dedd42a57560c79ec8be22d62a57:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_05_27.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_04.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/3e439cce6082cce520b4d345a06be8c6-040f65ed7e31e894350cbbcf60651009:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_04.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_05_28.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/ca00047d1cee36fccbf76e17d9403bfa-459baf7be44901d73eba561196d04199:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_05_28.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_05.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/7b3840c334ab778152edce08ec3a5d90-6035ed1d1526643fef882aa386f3df37:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_05.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_05_29.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/406422f70323d4359c7e55a8c06eec4a-e9ab4179b8a8c484ab6c5a3f8baf79ff:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_05_29.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_07.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/95b0361510c9d7d20728be0069518e09-64a31f444b3d20823398868759b14728:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_07.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_05_31.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/0ab0e86a40311fe195cc7afb29744618-d0f51bb539b431667bd99e9b4148d544:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_05_31.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_08.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/18843e60267a0a7fbc3b9dd04178838d-9d1554d82fa443ce8012e210ec7314ba:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_08.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_01.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/6855e68aedb010433af51dfdca08d94f-cc168723495d137daf70c72847b912af:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_01.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_09.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/8a1a6834020cdaabd9ada2466898e4b5-dd577dc2dc4f4c8c41d8d4379e2d010d:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_09.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_02.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/2170ee42bd2f5b38d6e26ce28377c7d4-b0b228114a59ecb6be8c111ae50ab827:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/2010_06_02.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/37c9520851df303423347af54fef16cf-0ab1d820ab098e79e7d1bdb18cac5454:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2109/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_14.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/1f673e4056e5b53d1da467cc8c27368e-b808fc033065f7d54af9f1a4bffe5d5e:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_14.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_07.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/5a2f4a556826c91018248a4ef28c1748-fae939d34b914bb1c17b740f3f4e7889:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_07.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_15.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/4406af15cdf77860c6843e489fa897ab-48af4dab3d121124f2602e2f55d378c5:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_15.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_08.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/ca833cad224d3b755e0eca22de955080-24e6ffa21c4ccdfbe0c57809f493b460:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_08.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_16.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/aafca77e08a4efae61ad175b6b30b088-66f1af9e22497076959aa93c48f3a95e:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_16.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_09.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/18ad9e0838d92cec207f64e53699f1d8-6eeb2eb8ac4c310f04458f12e6cecdd8:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_09.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_17.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/366494e967442349e8a1c5fecc247b0a-3c99ae9d697cbb862f08672560a18485:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_17.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_10.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/c6240455e647365624e1ee5befebee5b-579d718f6063a452f7bb7e871ce78e24:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_10.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_18.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/4ea6090b1bb3e295b9d8325b71ecefda-72db1e07b78e58aff521e4c471fe770c:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_18.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_11.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/807a1a938d006023466058aac9eda83c-2eb20d06968c71a9b51bc958cdee466f:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_11.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_19.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/87ac2ba77ee4e9d54efbffc4e4887f2c-6e57e81dc4a50b15fd0dd71fd4cf3b37:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_19.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_12.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/541ff7b1c1425d6ada4e77065fee3073-3d687eaeeb0451ae6d8af429f6bf4b57:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_12.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_20.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/933904a58d2b98508a735d919fad7c45-ec2d6b2ab6323c74e9d9452d263ee7a2:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_20.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_13.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/6158d7f6275237a254c39c29c7137cda-2ce5227840e9ac76f6385f1001fa7297:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/2010_10_13.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a91e566234166c587c27c2ec270deb4e-109391727f49665bd2c6bcd1faf28fe4:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2128/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_02.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/402da8800a7a398727bc039075d3ece2-df41817937d95f84dc7043c15acd9c2a:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_02.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_26.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/847c7ca6807926646b429bae9b10a166-ebdb91931769afcdf8fcbb2833d4cdaa:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_26.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_03.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/ff8eb6d494f172ea2b62b98eac33a9e0-7303be58007658089a6954cce38ba4b3:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_03.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_27.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/2c3020fbe0404848a3cbf470ba493710-4647759cdd800fdf6c00270a35d3379c:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_27.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_04.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a2bf88c13bad56d0e90afc243ffa2ad5-27cda914a25e43b842dc47ae399b5d50:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_04.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_28.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/83377ccdfd5cdaf67dc332c553b8674c-c9d91841351ca4562cd6f7201bbf6863:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_28.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_05.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/16bcc61bbfa5900edc8250a9cfc274d2-b469d30bc2e89e5f664ee8cc496c04eb:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_05.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_29.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/2e2345390373c2c7ee8c3cac84e1ee21-41cfc4e81bb020a30dbb13fdc74bac09:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_29.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_06.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/4eccc35f7af86a4c4b956c3857ba5077-dc83cbe241bc827974313199b5f77868:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_06.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_30.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/0a6f91eafb8cf0a6f2244df10d0c3776-5431c6c2b7a3947496efb8ed0ee2b55b:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_30.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_07.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/7f18dadfe2a61c27afb5a38ff02096d4-e1cad9b29421ebd631235413fa80edfb:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_07.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_31.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/9692579b791d1a26cd41bb9fcf408c7c-be0c61fc3fc5367d6d4edc791fb98157:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_05_31.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_08.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/9df41d68eb68ec505d894f1deb8a5caf-c3fb45fca823d92317be7406f745945c:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_08.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_01.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/66c9c676dafdad9297d320a0c2478c5a-da4771fe25b5b015682334696b92d737:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/2011_06_01.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/7ca635bf4264eb34a33ad1c00cd1d34e-0622771531e5986f06e9ffd41977153f:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA12/2161/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python\n",
    "\n",
    "## MSC_Thesis \n",
    "## Jacotte Monroe \n",
    "## 19/03/24\n",
    "\n",
    "## Script that reads the spatial and temporal extents and retrieves the matching MODIS 250m images. \n",
    "## MODIS dataset is cloudmasked using a bitmask from MODIS 500m, then gap filled using temporal linear interpolation. \n",
    "## Each image is reprojected to EPSG 32733 (Namibia projection) and clipped to study area. \n",
    "## NDVI is calculated. \n",
    "## Script inputs: \n",
    "##       0_single_run_settings.csv\n",
    "##       2_a1_step_extents.csv\n",
    "## Script outputs: \n",
    "##       3_a1_modis_images (folder) > [daily_MODIS_NDVI_250m_date].tif (intermediate output) & 3_a2_modis_ndvi.tif (intermediate output)\n",
    "\n",
    " \n",
    "\n",
    "###########\n",
    "## Script set-up and loading necessary libraries \n",
    "###########\n",
    "\n",
    "import ee\n",
    "ee.Authenticate()\n",
    "\n",
    "import geemap\n",
    "import os\n",
    "import pandas as pd\n",
    "import math \n",
    "\n",
    "ee.Initialize()\n",
    "\n",
    "\n",
    "\n",
    "###########\n",
    "## Functions needed to run the script \n",
    "###########\n",
    "\n",
    "# function to extract and combined relevant QA band bits/flags \n",
    "# source: https://mygeoblog.com/2017/09/08/modis-cloud-masking/\n",
    "def getQABits(image, start_bit, end_bit, band_name):\n",
    "    pattern = 0\n",
    "    \n",
    "    # for each bit/flag of the QA band --> assign new value to its bits \n",
    "    # so each flag will have a different value and the pixel will be the sum of all flags \n",
    "    for i in range(start_bit, end_bit):\n",
    "        pattern += math.pow(2,i)\n",
    "    # return single band image of extracted QA bits\n",
    "    # source: https://developers.google.com/earth-engine/apidocs/ee-image-bitwiseand\n",
    "    return image.select([0], [band_name]) \\\n",
    "                .bitwiseAnd(pattern) \\\n",
    "                .rightShift(start_bit)\n",
    "\n",
    "\n",
    "\n",
    "# function to mask out cloudy pixels \n",
    "# source: https://gis.stackexchange.com/questions/308456/get-a-mask-for-modis-250m-mod09gq-using-modis-500m-mod09ga-in-google-earth\n",
    "# source: https://mygeoblog.com/2017/09/08/modis-cloud-masking/\n",
    "def maskClouds(image):\n",
    "    # selects the MODIS 500m QA band \n",
    "    QA = image.select('state_1km')\n",
    "\n",
    "    # creates a cloud&shadow flag from specified bits --> in this case: 'Cloud state' and 'Cloud shadow'\n",
    "    pixelQuality = getQABits(QA, 0, 2, 'cloud_and_shadow_quality_flag')\n",
    "\n",
    "    # returns image masking out cloudy pixels \n",
    "    return image.updateMask(pixelQuality.eq(0))\n",
    "\n",
    "\n",
    "\n",
    "# function to add timestamp band to image\n",
    "# source: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "def addTimestamp(image): \n",
    "    # create new image where pixel value = time of original image\n",
    "    timeImage = image.metadata('system:time_start').rename('timestamp')\n",
    "\n",
    "    # mask new time image with original image to remove cloudmasked pixels\n",
    "    timeImageMasked = timeImage.updateMask(image.mask().select(0))\n",
    "\n",
    "    # return original image with time image as new band \n",
    "    return image.addBands(timeImageMasked)\n",
    "\n",
    "\n",
    "\n",
    "# function that takes image and replaces masked pixels with linearly interpolated values from bef/aft images\n",
    "def interpolateImage(image):\n",
    "    image = ee.Image(image)\n",
    "\n",
    "    # get list of before/after images from image property\n",
    "    beforeImages = ee.List(image.get('before'))\n",
    "    afterImages = ee.List(image.get('after'))\n",
    "\n",
    "    # create image collection of before/after images\n",
    "    # mosaic() combines images into one image accordint to their position in collection \n",
    "    #  image first has all pixels from last image in collection \n",
    "    #  gaps filled with second to last image from collection ...\n",
    "    beforeMosaic = ee.ImageCollection.fromImages(beforeImages).mosaic()\n",
    "    afterMosaic = ee.ImageCollection.fromImages(afterImages).mosaic()\n",
    "\n",
    "    # rename time band of images \n",
    "    time_bef = beforeMosaic.select('timestamp').rename('time_bef')\n",
    "    time_aft = afterMosaic.select('timestamp').rename('time_aft')\n",
    "    time0 = image.metadata('system:time_start').rename('time0')\n",
    "\n",
    "    # combine all three single band time images into one image with three time bands \n",
    "    timeImage = ee.Image.cat([time_bef, time_aft, time0])\n",
    "\n",
    "    # compute image of interpolated surface reflectance values \n",
    "    timeRatio = timeImage.expression('(time0 - time_bef) / (time_aft - time_bef)', \\\n",
    "                    {'time0': timeImage.select('time0'), \n",
    "                     'time_bef': timeImage.select('time_bef'), \n",
    "                     'time_aft': timeImage.select('time_aft')})\n",
    "\n",
    "    interpolated = beforeMosaic.add((afterMosaic.subtract(beforeMosaic).multiply(timeRatio)))\n",
    "\n",
    "    # replace masked pixels in current image with pixels from interpolated mosaic\n",
    "    result = image.unmask(interpolated)\n",
    "\n",
    "    # return gap-filled image\n",
    "    return result.copyProperties(image, ['system:time_start'])\n",
    "\n",
    "\n",
    "\n",
    "# function to reproject (elephant fixes reprojected from 4326 to 32733 same needs to be done to images) \n",
    "def reprojectModis(image):\n",
    "    return image.reproject('EPSG:32733', None, 250)\n",
    "\n",
    "\n",
    "\n",
    "# function to clip image to study area\n",
    "# have to include nested function because can't use map() with more than one argument \n",
    "# source: https://gis.stackexchange.com/questions/473500/mapping-function-with-multiple-arguments-in-google-earth-engine\n",
    "def clipToAOI(bbox): \n",
    "    def withBbox(image):\n",
    "        return image.clip(bbox).copyProperties(image, ['system:id'])\n",
    "    return withBbox\n",
    "\n",
    "\n",
    "\n",
    "# function to calculate NDVI \n",
    "def addNDVI(image): \n",
    "    ndvi = image.normalizedDifference(['nir', 'red']).rename('NDVI')\n",
    "    return image.addBands(ndvi)\n",
    "\n",
    "\n",
    "\n",
    "def retrieveMODISImages(): \n",
    "    # source: https://stackoverflow.com/questions/44116194/import-a-function-from-another-ipynb-file\n",
    "    #from ipynb.fs.defs.pythonFunctions import getQABits, maskClouds, addTimestamp, interpolateImage, reprojectMODIS, clipToAOI, addNDVI\n",
    "    \n",
    "    ###########\n",
    "    ## Read run settings \n",
    "    ###########\n",
    "    run_settings_table = pd.read_csv('data/single_run_settings.csv', index_col = 0, header = None)\n",
    "\n",
    "    ID = run_settings_table.iloc[0,0]\n",
    "    week = str(run_settings_table.iloc[0,1])\n",
    "    random_data_method = run_settings_table.iloc[0,2]\n",
    "\n",
    "\n",
    "\n",
    "    ###########\n",
    "    ## Load step extents LUT\n",
    "    ###########\n",
    "    extents_lut = pd.read_csv('data/' + ID + '/' + week + '/' + '2_a1_step_extents_LUT_' + random_data_method + '.csv')\n",
    "\n",
    "\n",
    "\n",
    "    ###########\n",
    "    ## Create region (largest extent) geometry and define first and last dates\n",
    "    ###########\n",
    "    large_extent = extents_lut.iloc[-1]\n",
    "\n",
    "    large_extent_coords = [[[large_extent.loc['xmin'], large_extent.loc['ymin']],\n",
    "                            [large_extent.loc['xmin'], large_extent.loc['ymax']],\n",
    "                            [large_extent.loc['xmax'], large_extent.loc['ymax']],\n",
    "                            [large_extent.loc['xmax'], large_extent.loc['ymin']]]]\n",
    "    \n",
    "    large_region = ee.Geometry.Polygon(large_extent_coords, proj = 'EPSG:32733', evenOdd = False)\n",
    "    \n",
    "    first_date = ee.Date(large_extent.loc['start_date_prev_week'], 'Africa/Maputo')\n",
    "    week_start_date = ee.Date(large_extent.loc['start_date'], 'Africa/Maputo')\n",
    "    last_date = ee.Date(large_extent.loc['end_date'], 'Africa/Maputo')\n",
    "\n",
    "\n",
    "    \n",
    "    ###########\n",
    "    ## Load feature of Etosha National Park (Namibia) and transform into geometry\n",
    "    ###########\n",
    "    # load Etosha National Park study area\n",
    "    enp = ee.FeatureCollection('WCMC/WDPA/current/polygons') \\\n",
    "            .filter(ee.Filter.eq('ORIG_NAME', 'Etosha'))\n",
    "    \n",
    "    # turn ENP study area into a geometry\n",
    "    enp_geom = enp.geometry()\n",
    "\n",
    "\n",
    "    \n",
    "    ###########\n",
    "    ## Set interpolation parameters \n",
    "    ###########\n",
    "    # set time-window for interpolation (how far will interpolate)\n",
    "    # source: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "    days = ee.Number(30) \n",
    "    \n",
    "    # convert to milliseconds (for gap filling step)\n",
    "    millis = days.multiply(1000*60*60*24)\n",
    "\n",
    "\n",
    "    \n",
    "    ###########\n",
    "    ## Define path of output directory \n",
    "    ###########\n",
    "    # define output folder paths for current MODIS images and images from week prior\n",
    "    out_dir = 'data/' + ID + '/' + week + '/' + '3_a1_modis_images_' + random_data_method + '/'\n",
    "    \n",
    "    \n",
    "    \n",
    "    ###########\n",
    "    ## Retrieve MODIS datasets and combine into one dataset\n",
    "    ###########\n",
    "    # load MODIS 250m dataset \n",
    "    # take larger time range to include images for gap filling of cloudmasked pixels \n",
    "    # source: https://developers.google.com/earth-engine/apidocs/ee-date-advance#colab-python\n",
    "    modis_250 = ee.ImageCollection('MODIS/061/MOD09GQ') \\\n",
    "            .filterDate(first_date.advance(days.multiply(-1), 'day'), last_date.advance(days, 'day')) \\\n",
    "            .filterBounds(enp_geom)\n",
    "    \n",
    "    # import MODIS 500m dataset (contains information for cloudmasking)\n",
    "    modis_500 = ee.ImageCollection('MODIS/006/MOD09GA') \\\n",
    "            .filterDate(first_date.advance(days.multiply(-1), 'day'), last_date.advance(days, 'day'))  \\\n",
    "            .filterBounds(enp_geom)\n",
    "    \n",
    "    # combine datasets\n",
    "    # pixel with certain MODIS 500m value can be selected for MODIS 250m \n",
    "    # source: https://gis.stackexchange.com/questions/308456/get-a-mask-for-modis-250m-mod09gq-using-modis-500m-mod09ga-in-google-earth\n",
    "    modis_combined = modis_500.combine(modis_250)\n",
    "    \n",
    "    # new name of MODIS 250m bands (to avoid having two of similar name)\n",
    "    modisBands = ['sur_refl_b01_1', 'sur_refl_b02_1']\n",
    "    renamedBands = ['red', 'nir']\n",
    "\n",
    "\n",
    "\n",
    "    ###########\n",
    "    ## Create cloud free MODIS 250m dataset\n",
    "    ###########\n",
    "    # source: https://mygeoblog.com/2017/09/08/modis-cloud-masking/ \n",
    "    # source: https://gis.stackexchange.com/questions/308456/get-a-mask-for-modis-250m-mod09gq-using-modis-500m-mod09ga-in-google-earth\n",
    "    \n",
    "    modis_cloudFree = modis_combined.map(maskClouds).select(modisBands, renamedBands)\n",
    "\n",
    "    \n",
    "    ###########\n",
    "    ## Image gap filling - Linear interpolation of missing pixels \n",
    "    ###########\n",
    "    # add timestamp band to each image \n",
    "    modis_cloudFree_withTime = modis_cloudFree.map(addTimestamp)\n",
    "    \n",
    "    # following tutorial: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "    # define filter to only retrieve images within the specified time-window\n",
    "    maxDiffFilter = ee.Filter.maxDifference(difference = millis, \n",
    "                                            leftField = 'system:time_start', \n",
    "                                            rightField = 'system:time_start')\n",
    "    \n",
    "    # define filters that compare given image timestamp against other image timestamps\n",
    "    # NOTE: leftField compared against rightField --> so in first filter = leftField smaller than rightField\n",
    "    greaterEqFilter = ee.Filter.greaterThanOrEquals(leftField = 'system:time_start', \n",
    "                                                    rightField = 'system:time_start')\n",
    "    \n",
    "    lessEqFilter = ee.Filter.lessThanOrEquals(leftField = 'system:time_start', \n",
    "                                              rightField = 'system:time_start')\n",
    "    \n",
    "    # combined filters --> find all images before/after image that are within time-window\n",
    "    filter_before = ee.Filter.And(maxDiffFilter, greaterEqFilter)\n",
    "    filter_after = ee.Filter.And(maxDiffFilter, lessEqFilter)\n",
    "    \n",
    "    # set join parameters\n",
    "    # pairs each image to group of matching elements from the second collection \n",
    "    # saves the matching elements as new property with matchesKey name, ordered by date\n",
    "    # order set to have the closest image as last element in list\n",
    "    # source: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "    # source: https://developers.google.com/earth-engine/apidocs/ee-join-saveall\n",
    "    join_before = ee.Join.saveAll(\n",
    "        matchesKey = 'before', \n",
    "        ordering = 'system:time_start', \n",
    "        ascending = True)\n",
    "    \n",
    "    join_after = ee.Join.saveAll(\n",
    "        matchesKey = 'after', \n",
    "        ordering = 'system:time_start', \n",
    "        ascending = False)\n",
    "    \n",
    "    # join the cloudfree MODIS 250m collection with itself to get all previous/post images within time-window\n",
    "    # results in image collection where each image has a property that lists all images preceeding/following image within time-window\n",
    "    # source: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "    modis_joined_temp = join_before.apply(\n",
    "        primary = modis_cloudFree_withTime, \n",
    "        secondary = modis_cloudFree_withTime, \n",
    "        condition = filter_before)\n",
    "    \n",
    "    modis_joined = join_after.apply(\n",
    "        primary = modis_joined_temp, \n",
    "        secondary = modis_joined_temp, \n",
    "        condition = filter_after)\n",
    "    \n",
    "    # interpolate all images from MODIS 250m image collection\n",
    "    modis_interpolated = ee.ImageCollection(modis_joined.map(interpolateImage))\n",
    "    \n",
    "    \n",
    "    \n",
    "    ###########\n",
    "    ## Look over each step extent entry in the LUT to export corresponding image \n",
    "    ###########\n",
    "    # 1. get dates\n",
    "    # 2. get coordinates \n",
    "    # 3. turn into geometry\n",
    "    # 4. get MODIS image\n",
    "    # 5. reproject \n",
    "    # 6. clip\n",
    "    # 7. calculate NDVI\n",
    "    # 8. export image\n",
    "    \n",
    "    for i in range(len(extents_lut)-1):\n",
    "        # select entry\n",
    "        extent = extents_lut.iloc[i]\n",
    "        \n",
    "        # retrieve extent dates \n",
    "        start_date = extent.loc['start_date']\n",
    "        end_date = extent.loc['end_date']\n",
    "        \n",
    "        start_date_prev_week = extent.loc['start_date_prev_week']\n",
    "        end_date_prev_week = extent.loc['end_date_prev_week']\n",
    "        \n",
    "        # retrieve extent coordinates \n",
    "        # source: https://sparkbyexamples.com/pandas/pandas-get-cell-value-from-dataframe/?utm_content=cmp-true\n",
    "        # source: https://stackoverflow.com/questions/75203044/how-to-create-polygon-from-bbox-data-in-pythonv\n",
    "        coords = [[[extent.loc['xmin'], extent.loc['ymin']],\n",
    "                  [extent.loc['xmin'], extent.loc['ymax']],\n",
    "                  [extent.loc['xmax'], extent.loc['ymax']],\n",
    "                  [extent.loc['xmax'], extent.loc['ymin']]]]\n",
    "    \n",
    "        # create geometry from coordinates\n",
    "        bbox = ee.Geometry.Polygon(coords, proj = 'EPSG:32733', evenOdd = False)\n",
    "        \n",
    "        # retrieve MODIS 250m image for geometry \n",
    "        modis = modis_interpolated \\\n",
    "            .filterDate(start_date, end_date) \\\n",
    "            .filterBounds(enp_geom) \\\n",
    "            .select(['nir', 'red']) \n",
    "        \n",
    "        modis_prev_week = modis_interpolated \\\n",
    "            .filterDate(start_date_prev_week, end_date_prev_week) \\\n",
    "            .filterBounds(enp_geom) \\\n",
    "            .select(['nir', 'red']) \n",
    "        \n",
    "        # reproject image\n",
    "        modis_reproj = modis.map(reprojectModis)\n",
    "        \n",
    "        modis_prev_week_reproj = modis_prev_week.map(reprojectModis)\n",
    "        \n",
    "        # clip image\n",
    "        modis_clipped = modis_reproj.map(clipToAOI(bbox))\n",
    "        \n",
    "        modis_prev_week_clipped = modis_prev_week_reproj.map(clipToAOI(bbox))\n",
    "    \n",
    "        # calculate NDVI \n",
    "        modis_ndvi = modis_clipped.map(addNDVI).select(['NDVI'])\n",
    "    \n",
    "        modis_ndvi_prev_week = modis_prev_week_clipped.map(addNDVI).select(['NDVI'])\n",
    "        \n",
    "        # export MODIS image to local repository \n",
    "        # source: https://github.com/gee-community/geemap/blob/master/examples/notebooks/11_export_image.ipynb\n",
    "        geemap.ee_export_image_collection(modis_ndvi, out_dir = out_dir, region = large_region)\n",
    "        \n",
    "        geemap.ee_export_image_collection(modis_ndvi_prev_week, out_dir = out_dir, region = large_region)\n",
    "    \n",
    "    \n",
    "    \n",
    "    ###########\n",
    "    ## Create and export mean NDVI image for large extent \n",
    "    ###########\n",
    "    # This image will be used as basemap for visualization (no analysis done with it)\n",
    "    # filter dataset to dates\n",
    "    modis_week = modis_interpolated \\\n",
    "        .filterDate(week_start_date, last_date) \\\n",
    "        .filterBounds(enp_geom).select(['nir', 'red']) \n",
    "    \n",
    "    # calculate NDVI \n",
    "    modis_week_ndvi = modis_week.map(addNDVI).select(['NDVI'])\n",
    "    \n",
    "    # create mean NDVI raster\n",
    "    # source: https://developers.google.com/earth-engine/guides/ic_reducing\n",
    "    modis_ndvi_mean = modis_week_ndvi.mean()\n",
    "    \n",
    "    # reproject image\n",
    "    modis_ndvi_mean = modis_ndvi_mean.reproject('EPSG:32733', None, 250)\n",
    "    \n",
    "    # clip image\n",
    "    modis_ndvi_mean = modis_ndvi_mean.clip(large_region)\n",
    "    \n",
    "    # export image\n",
    "    geemap.ee_export_image(modis_ndvi_mean, filename = os.path.join(out_dir, \"mean_ndvi.tif\"), region = large_region, scale = 250)\n",
    "\n",
    "    return print('(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.')\n",
    "    #print('Now extracting covariates...')\n",
    "\n",
    "\n",
    "# read the table with all run settings\n",
    "all_runs = pd.read_csv('data/run_settings_RQ2_rerun.csv', index_col = 0)\n",
    "\n",
    "# iteratte over each entry in the table \n",
    "for i in range(len(all_runs)):\n",
    "    # save the run settings to be read in the function\n",
    "    row = all_runs.iloc[[i]]\n",
    "    row.to_csv('data/single_run_settings.csv', header = False)\n",
    "\n",
    "    # run function for MODIS image retrieval\n",
    "    retrieveMODISImages()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
