{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7c722758-e97b-48c9-a3f5-9f4c63ac3725",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_01.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/3a90694880637f783b085119789b3b76-90844ab1b8c01d2d6845b54a2929a94f:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_01.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_25.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/2f5dc08276942baa8855dcef1ca40faf-999be2f5486e115b1c40e54195616452:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_25.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_02.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/f5bea684dbc8abb7a183e67bc2bc8ea4-54f9cdc6fe51ff10a379c3b0cd26e253:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_02.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_26.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/439d9d6f2c86be9cc9dda00fe5c8f2f3-8edc81efd2dd588de52186bcb0d4f654:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_26.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_03.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/b52b6df461a9c36c0b291b6b0a3ac685-e3cf4e184fa82cbb7c01a4777235d320:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_03.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_27.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/c2dd2c08d61bf4f2c738f9fb95eed46d-e39e105d77365e83066dbaec0f9d7878:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_27.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_04.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/28f9e46b4d4839f3f3a1f7936df82e55-7202c6772dfb7ec17b4b3cfdbecb962c:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_04.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_28.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/bfc433dbbdc4001335c9a8e479b9d184-3345a7a6210f1b079727d88f57e2c0a5:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_28.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_05.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/4b421df9f8a9d96b23f11799e7d29603-1abc7ec2c97064910d2a0ea72d1dd6e9:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_08_05.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_29.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/fb3f87aac468d033725eb36f9618093d-1eb673502a23a729b85bdb5ecb9d4ed1:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/2009_07_29.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a03bfbe12e2b10fc4c31ad404b7c59ed-0c000014459fab9c4046f915d3a8f0b5:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2065/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_29.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/59720f5fc5c20c7a42d02c56f8170087-cdd46532f490f8db9cb1b175e9855cae:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_29.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_22.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/0e03278e9a5c21288e5b3e7af77ebbf0-b190f156ba23a867ed873a2bc404bc07:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_22.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_30.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/da264f159b8702bbce3a24984ab268b9-4b65d441e04212124a0eb6a47b66d0cb:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_30.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_23.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/c72283e6cc3f605f83ab2577f78b2129-e890ccf86d1c31f1aecde56fe173fd27:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_23.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_01.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/73a5e6daae791985ae48947d533a2782-6fe4a0fb033196db944647902a963660:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_01.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_24.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/8ae35103d4615614f24614b33c352e02-4b6495c05b207c5ef67a0724daf9d6d7:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_24.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_02.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/739c516d393250f3fd4ac8f9a6436890-cc0244fd3d69e33da0758b48d3ba6026:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_02.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_25.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/77bb9a3e8d9c2acb8afc47d871102fd4-dc29dd12d8c11896d5706ec30cb64096:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_25.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_03.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/dce9bbb041f04e0606b5f3214b4b8923-c78d73918b3553cd913342de088223ab:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_03.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_26.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a6b94dc64670aedf6104829b8b03769c-1157ae357ad635bb8df2301bd9a42d54:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_26.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_04.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/89323575028a080395054d9330645c68-dc26a0162b62197af17e9850c6e8f9cf:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_04.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_27.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/720e9eba9307ca66ce2c31c38889013a-a5c0fef80b5f5b092ee8a5da56656818:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_27.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_05.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/769b918938d47d6d8c81428b0d84fa34-820cb67a664d83fc7055f97f7955339b:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_05_05.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_28.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/6e0c4b8ee737c36d084304b1a5d07de1-e9674ced607362e2fc4f6cac44af48c2:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/2010_04_28.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/be46cfaa5d7f0eb9a64550029a2427de-570f8070adcc0503885804e5c6406f03:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2104/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_09.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/76f64b5e5ed929a55df0ee36482085c3-331201f16e80553b14e6d91468fa3dce:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_09.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_02.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/ba1309acc8a174706ff8132462932e56-cd347f990e238665ad6d6ff17ee0e3b1:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_02.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_10.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/471f23a214ca59c29de4257f0910889f-18b0c8f567ee73a10cd16b03359340df:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_10.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_03.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a87a9bbb2720e42624ab21520eb2e2b1-dd3dfad9794fb5695d31c72f9322860b:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_03.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_11.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/120b4ed812680e456cbbcbc92b30c633-dcec8dd418838b32a089141d88c1bc7a:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_11.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_04.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/d421da32c71381f818c893b2e50e64fa-d7b987dd45921ad61a4b2f6a607d2284:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_04.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_12.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/d51a201907796b6340bbdc41b2fe058d-0b1320e2f04fcb11a1a44f39db1c6e8e:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_12.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_05.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/568c8e7f25bbbc48e7351edbf5b67c0e-2acb0f2d5611836ba776c99b8c1002b7:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_05.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_13.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a753d296a98ff004dcf22f09972d7749-5329250fe02f2a3d87f180ae9c9a0ff7:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_13.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_06.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/e7519527a70a2cb207490f414962229b-9c4db45a0ec57ec33b5f3170973ee181:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_06.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_14.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/54110790afb485c6a8fe6a102871acc5-f66751172b03494c0cae91b4e9cdd3d5:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_14.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_07.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/90c87a28dae5c9d9a25000a626a42fac-ae134f76c9f02f505ff18a891491a1a7:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_07.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_15.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/07b5028509b02c0360d861886391e5b2-7d77d598652933ab26b6ba1e33bb7c2f:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_15.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_08.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/8a90bf5e79e16e9bde236c3f4fbd6f05-d4540f76d625511fc14604b3712c4045:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/2010_09_08.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/5c83d5c682115e0eb2a3540026d0243b-82f52c51c3f13865e75456f678703f6a:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2123/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_25.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/65c97456ffabb549e7730c21b7ef3703-f37e7b0374c338aaf87ff97843c79777:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_25.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_18.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/fe3529b3d028200127bfbc8ae27a8b6b-e1df812747b1c3224dc082666569d703:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_18.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_26.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/7ba9506a5b4340799797fd0b1217814a-fcbb36f74b5f04f53e06e45fd62f4948:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_26.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_19.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/01f6ee5ba1b7ce1830e9c09dc07285b9-ee717e68df798111b304c725de1b3944:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_19.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_27.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/f90f94f5e89bfb61311839a007a7a3ae-a347488c830164580a36ad89cd2af177:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_27.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_20.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/9bb0454f1b2e9ca58f197ce58ef00848-ca0bd8be180c28e3467bbefdcf594699:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_20.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_28.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/f08fa3beab1be629c7acd64100682017-0daab605da0815b81222955c876fc68d:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_28.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_21.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/32cadf69d1e116d4f9a042bbeacb8112-6435c499985a7a5aa62229dc220b964e:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_21.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_29.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/0f4e4d376d1cf5327752baee12098283-db46c10ce367a9b5c8f90d0caa6b593e:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_29.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_22.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/3fce9cb7451947f572f0fa77823f1c45-b83df4931de1a12e4c0cdeaece7b99a3:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_22.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_30.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/8ce44888f1fd8888690c0ad0d7d5b013-83facbe626efda787313a36ce77aa7cd:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_30.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_23.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/95c2ab39f50b4de057d5c30be7c73bd6-6ea5d59f4bd69f3a9c94400f5ee9e94d:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_23.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_12_01.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/cbcc9a307c292d9b373e9e0f4e5d8d0d-40c6d3fd36dcb283aa9ed348c3323fcf:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_12_01.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_24.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/8dc82ec4b7bf63c26ba4c1049bddcfe1-4ff9b4e3f256e82bcdd4711001551449:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/2010_11_24.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/eb23c8089c59699309c63620eb38f3c8-e8f97993b064aa979bd5fe398467fd3c:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2134/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_16.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/19761f101dd101688e346bda052ce03b-8cdc9050dd42c1f46e24fe98c3b24c72:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_16.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_09.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/4575c7ecf2015b30423c81cde8cd3953-9cb68f61a5c619b3891c205ee555a44b:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_09.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_17.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/aa816934e4e5b605a6c817ea44cc43de-fa8d64060faf8f3b621b0ab8751eb202:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_17.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_10.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/f2f2c601bbb7809a35a67876e4724df4-60dbddc1f5458124926e3cb0c2be74ad:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_10.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_18.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/999ac9e9035c670de887c2274c361ba9-086ef2b51a9ebe6d13a131e984b0aab2:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_18.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_11.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/bb3c78f07649b91833fbec5dcbb7aec5-9e84c5d01ad1014c911734d00d668e1f:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_11.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_19.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/62e329cfb2bc010fed3a250bac913c37-4ad2e6c27c55eb349660242b3ef4ecde:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_19.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_12.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/8b615c4a28b7f26c79b687047de76a6a-a1ea1a0afe33d2b91231628683c1cd71:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_12.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_20.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/8bc020e3bfc208b9aab73b1202578f7b-1a93e4087c5daec5e98b651308626976:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_20.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_13.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/19220aa54d29e1f2eeb3a3367355fa77-62b7833b19f4e521fc7dc0a35aadfb78:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_13.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_21.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a6424961ad9dcf4c4ba6f120165e8e47-39de71496c255557ab246ebd5d867cf4:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_21.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_14.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/f3582aae924be5b7cd91cd2c4bd5d74b-056295bb14e810b3dbf64a01a2726e14:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_14.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_22.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/0f5f03bf1b693f2d05083666d2020542-0b0279b3bacbaa6a0af862b0293ad3ff:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_22.tif\n",
      "\n",
      "\n",
      "Total number of images: 1\n",
      "\n",
      "Exporting 1/1: data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_15.tif\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/a647a64c4c415b5e47c2cae3012d8981-a48f7ec2254954d2a763b1ac9114e8bc:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/2011_06_15.tif\n",
      "\n",
      "\n",
      "Generating URL ...\n",
      "Downloading data from https://earthengine.googleapis.com/v1/projects/earthengine-legacy/thumbnails/9b690578e0c00bf7a2968402983b1591-967a564e5e3842ced94375198620ad81:getPixels\n",
      "Please wait ...\n",
      "Data downloaded to /home/osboxes/Documents/MSc_Thesis/data/LA13/2163/3_a1_modis_images_random_path_custom_distr/mean_ndvi.tif\n",
      "(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python\n",
    "\n",
    "## MSC_Thesis \n",
    "## Jacotte Monroe \n",
    "## 19/03/24\n",
    "\n",
    "## Script that reads the spatial and temporal extents and retrieves the matching MODIS 250m images. \n",
    "## MODIS dataset is cloudmasked using a bitmask from MODIS 500m, then gap filled using temporal linear interpolation. \n",
    "## Each image is reprojected to EPSG 32733 (Namibia projection) and clipped to study area. \n",
    "## NDVI is calculated. \n",
    "## Script inputs: \n",
    "##       0_single_run_settings.csv\n",
    "##       2_a1_step_extents.csv\n",
    "## Script outputs: \n",
    "##       3_a1_modis_images (folder) > [daily_MODIS_NDVI_250m_date].tif (intermediate output) & 3_a2_modis_ndvi.tif (intermediate output)\n",
    "\n",
    " \n",
    "\n",
    "###########\n",
    "## Script set-up and loading necessary libraries \n",
    "###########\n",
    "\n",
    "import ee\n",
    "ee.Authenticate()\n",
    "\n",
    "import geemap\n",
    "import os\n",
    "import pandas as pd\n",
    "import math \n",
    "\n",
    "ee.Initialize()\n",
    "\n",
    "\n",
    "\n",
    "###########\n",
    "## Functions needed to run the script \n",
    "###########\n",
    "\n",
    "# function to extract and combined relevant QA band bits/flags \n",
    "# source: https://mygeoblog.com/2017/09/08/modis-cloud-masking/\n",
    "def getQABits(image, start_bit, end_bit, band_name):\n",
    "    pattern = 0\n",
    "    \n",
    "    # for each bit/flag of the QA band --> assign new value to its bits \n",
    "    # so each flag will have a different value and the pixel will be the sum of all flags \n",
    "    for i in range(start_bit, end_bit):\n",
    "        pattern += math.pow(2,i)\n",
    "    # return single band image of extracted QA bits\n",
    "    # source: https://developers.google.com/earth-engine/apidocs/ee-image-bitwiseand\n",
    "    return image.select([0], [band_name]) \\\n",
    "                .bitwiseAnd(pattern) \\\n",
    "                .rightShift(start_bit)\n",
    "\n",
    "\n",
    "\n",
    "# function to mask out cloudy pixels \n",
    "# source: https://gis.stackexchange.com/questions/308456/get-a-mask-for-modis-250m-mod09gq-using-modis-500m-mod09ga-in-google-earth\n",
    "# source: https://mygeoblog.com/2017/09/08/modis-cloud-masking/\n",
    "def maskClouds(image):\n",
    "    # selects the MODIS 500m QA band \n",
    "    QA = image.select('state_1km')\n",
    "\n",
    "    # creates a cloud&shadow flag from specified bits --> in this case: 'Cloud state' and 'Cloud shadow'\n",
    "    pixelQuality = getQABits(QA, 0, 2, 'cloud_and_shadow_quality_flag')\n",
    "\n",
    "    # returns image masking out cloudy pixels \n",
    "    return image.updateMask(pixelQuality.eq(0))\n",
    "\n",
    "\n",
    "\n",
    "# function to add timestamp band to image\n",
    "# source: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "def addTimestamp(image): \n",
    "    # create new image where pixel value = time of original image\n",
    "    timeImage = image.metadata('system:time_start').rename('timestamp')\n",
    "\n",
    "    # mask new time image with original image to remove cloudmasked pixels\n",
    "    timeImageMasked = timeImage.updateMask(image.mask().select(0))\n",
    "\n",
    "    # return original image with time image as new band \n",
    "    return image.addBands(timeImageMasked)\n",
    "\n",
    "\n",
    "\n",
    "# function that takes image and replaces masked pixels with linearly interpolated values from bef/aft images\n",
    "def interpolateImage(image):\n",
    "    image = ee.Image(image)\n",
    "\n",
    "    # get list of before/after images from image property\n",
    "    beforeImages = ee.List(image.get('before'))\n",
    "    afterImages = ee.List(image.get('after'))\n",
    "\n",
    "    # create image collection of before/after images\n",
    "    # mosaic() combines images into one image accordint to their position in collection \n",
    "    #  image first has all pixels from last image in collection \n",
    "    #  gaps filled with second to last image from collection ...\n",
    "    beforeMosaic = ee.ImageCollection.fromImages(beforeImages).mosaic()\n",
    "    afterMosaic = ee.ImageCollection.fromImages(afterImages).mosaic()\n",
    "\n",
    "    # rename time band of images \n",
    "    time_bef = beforeMosaic.select('timestamp').rename('time_bef')\n",
    "    time_aft = afterMosaic.select('timestamp').rename('time_aft')\n",
    "    time0 = image.metadata('system:time_start').rename('time0')\n",
    "\n",
    "    # combine all three single band time images into one image with three time bands \n",
    "    timeImage = ee.Image.cat([time_bef, time_aft, time0])\n",
    "\n",
    "    # compute image of interpolated surface reflectance values \n",
    "    timeRatio = timeImage.expression('(time0 - time_bef) / (time_aft - time_bef)', \\\n",
    "                    {'time0': timeImage.select('time0'), \n",
    "                     'time_bef': timeImage.select('time_bef'), \n",
    "                     'time_aft': timeImage.select('time_aft')})\n",
    "\n",
    "    interpolated = beforeMosaic.add((afterMosaic.subtract(beforeMosaic).multiply(timeRatio)))\n",
    "\n",
    "    # replace masked pixels in current image with pixels from interpolated mosaic\n",
    "    result = image.unmask(interpolated)\n",
    "\n",
    "    # return gap-filled image\n",
    "    return result.copyProperties(image, ['system:time_start'])\n",
    "\n",
    "\n",
    "\n",
    "# function to reproject (elephant fixes reprojected from 4326 to 32733 same needs to be done to images) \n",
    "def reprojectModis(image):\n",
    "    return image.reproject('EPSG:32733', None, 250)\n",
    "\n",
    "\n",
    "\n",
    "# function to clip image to study area\n",
    "# have to include nested function because can't use map() with more than one argument \n",
    "# source: https://gis.stackexchange.com/questions/473500/mapping-function-with-multiple-arguments-in-google-earth-engine\n",
    "def clipToAOI(bbox): \n",
    "    def withBbox(image):\n",
    "        return image.clip(bbox).copyProperties(image, ['system:id'])\n",
    "    return withBbox\n",
    "\n",
    "\n",
    "\n",
    "# function to calculate NDVI \n",
    "def addNDVI(image): \n",
    "    ndvi = image.normalizedDifference(['nir', 'red']).rename('NDVI')\n",
    "    return image.addBands(ndvi)\n",
    "\n",
    "\n",
    "\n",
    "def retrieveMODISImages(): \n",
    "    # source: https://stackoverflow.com/questions/44116194/import-a-function-from-another-ipynb-file\n",
    "    #from ipynb.fs.defs.pythonFunctions import getQABits, maskClouds, addTimestamp, interpolateImage, reprojectMODIS, clipToAOI, addNDVI\n",
    "    \n",
    "    ###########\n",
    "    ## Read run settings \n",
    "    ###########\n",
    "    run_settings_table = pd.read_csv('data/single_run_settings.csv', index_col = 0, header = None)\n",
    "\n",
    "    ID = run_settings_table.iloc[0,0]\n",
    "    week = str(run_settings_table.iloc[0,1])\n",
    "    random_data_method = run_settings_table.iloc[0,2]\n",
    "\n",
    "\n",
    "\n",
    "    ###########\n",
    "    ## Load step extents LUT\n",
    "    ###########\n",
    "    extents_lut = pd.read_csv('data/' + ID + '/' + week + '/' + '2_a1_step_extents_LUT_' + random_data_method + '.csv')\n",
    "\n",
    "\n",
    "\n",
    "    ###########\n",
    "    ## Create region (largest extent) geometry and define first and last dates\n",
    "    ###########\n",
    "    large_extent = extents_lut.iloc[-1]\n",
    "\n",
    "    large_extent_coords = [[[large_extent.loc['xmin'], large_extent.loc['ymin']],\n",
    "                            [large_extent.loc['xmin'], large_extent.loc['ymax']],\n",
    "                            [large_extent.loc['xmax'], large_extent.loc['ymax']],\n",
    "                            [large_extent.loc['xmax'], large_extent.loc['ymin']]]]\n",
    "    \n",
    "    large_region = ee.Geometry.Polygon(large_extent_coords, proj = 'EPSG:32733', evenOdd = False)\n",
    "    \n",
    "    first_date = ee.Date(large_extent.loc['start_date_prev_week'], 'Africa/Maputo')\n",
    "    week_start_date = ee.Date(large_extent.loc['start_date'], 'Africa/Maputo')\n",
    "    last_date = ee.Date(large_extent.loc['end_date'], 'Africa/Maputo')\n",
    "\n",
    "\n",
    "    \n",
    "    ###########\n",
    "    ## Load feature of Etosha National Park (Namibia) and transform into geometry\n",
    "    ###########\n",
    "    # load Etosha National Park study area\n",
    "    enp = ee.FeatureCollection('WCMC/WDPA/current/polygons') \\\n",
    "            .filter(ee.Filter.eq('ORIG_NAME', 'Etosha'))\n",
    "    \n",
    "    # turn ENP study area into a geometry\n",
    "    enp_geom = enp.geometry()\n",
    "\n",
    "\n",
    "    \n",
    "    ###########\n",
    "    ## Set interpolation parameters \n",
    "    ###########\n",
    "    # set time-window for interpolation (how far will interpolate)\n",
    "    # source: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "    days = ee.Number(30) \n",
    "    \n",
    "    # convert to milliseconds (for gap filling step)\n",
    "    millis = days.multiply(1000*60*60*24)\n",
    "\n",
    "\n",
    "    \n",
    "    ###########\n",
    "    ## Define path of output directory \n",
    "    ###########\n",
    "    # define output folder paths for current MODIS images and images from week prior\n",
    "    out_dir = 'data/' + ID + '/' + week + '/' + '3_a1_modis_images_' + random_data_method + '/'\n",
    "    \n",
    "    \n",
    "    \n",
    "    ###########\n",
    "    ## Retrieve MODIS datasets and combine into one dataset\n",
    "    ###########\n",
    "    # load MODIS 250m dataset \n",
    "    # take larger time range to include images for gap filling of cloudmasked pixels \n",
    "    # source: https://developers.google.com/earth-engine/apidocs/ee-date-advance#colab-python\n",
    "    modis_250 = ee.ImageCollection('MODIS/061/MOD09GQ') \\\n",
    "            .filterDate(first_date.advance(days.multiply(-1), 'day'), last_date.advance(days, 'day')) \\\n",
    "            .filterBounds(enp_geom)\n",
    "    \n",
    "    # import MODIS 500m dataset (contains information for cloudmasking)\n",
    "    modis_500 = ee.ImageCollection('MODIS/006/MOD09GA') \\\n",
    "            .filterDate(first_date.advance(days.multiply(-1), 'day'), last_date.advance(days, 'day'))  \\\n",
    "            .filterBounds(enp_geom)\n",
    "    \n",
    "    # combine datasets\n",
    "    # pixel with certain MODIS 500m value can be selected for MODIS 250m \n",
    "    # source: https://gis.stackexchange.com/questions/308456/get-a-mask-for-modis-250m-mod09gq-using-modis-500m-mod09ga-in-google-earth\n",
    "    modis_combined = modis_500.combine(modis_250)\n",
    "    \n",
    "    # new name of MODIS 250m bands (to avoid having two of similar name)\n",
    "    modisBands = ['sur_refl_b01_1', 'sur_refl_b02_1']\n",
    "    renamedBands = ['red', 'nir']\n",
    "\n",
    "\n",
    "\n",
    "    ###########\n",
    "    ## Create cloud free MODIS 250m dataset\n",
    "    ###########\n",
    "    # source: https://mygeoblog.com/2017/09/08/modis-cloud-masking/ \n",
    "    # source: https://gis.stackexchange.com/questions/308456/get-a-mask-for-modis-250m-mod09gq-using-modis-500m-mod09ga-in-google-earth\n",
    "    \n",
    "    modis_cloudFree = modis_combined.map(maskClouds).select(modisBands, renamedBands)\n",
    "\n",
    "    \n",
    "    ###########\n",
    "    ## Image gap filling - Linear interpolation of missing pixels \n",
    "    ###########\n",
    "    # add timestamp band to each image \n",
    "    modis_cloudFree_withTime = modis_cloudFree.map(addTimestamp)\n",
    "    \n",
    "    # following tutorial: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "    # define filter to only retrieve images within the specified time-window\n",
    "    maxDiffFilter = ee.Filter.maxDifference(difference = millis, \n",
    "                                            leftField = 'system:time_start', \n",
    "                                            rightField = 'system:time_start')\n",
    "    \n",
    "    # define filters that compare given image timestamp against other image timestamps\n",
    "    # NOTE: leftField compared against rightField --> so in first filter = leftField smaller than rightField\n",
    "    greaterEqFilter = ee.Filter.greaterThanOrEquals(leftField = 'system:time_start', \n",
    "                                                    rightField = 'system:time_start')\n",
    "    \n",
    "    lessEqFilter = ee.Filter.lessThanOrEquals(leftField = 'system:time_start', \n",
    "                                              rightField = 'system:time_start')\n",
    "    \n",
    "    # combined filters --> find all images before/after image that are within time-window\n",
    "    filter_before = ee.Filter.And(maxDiffFilter, greaterEqFilter)\n",
    "    filter_after = ee.Filter.And(maxDiffFilter, lessEqFilter)\n",
    "    \n",
    "    # set join parameters\n",
    "    # pairs each image to group of matching elements from the second collection \n",
    "    # saves the matching elements as new property with matchesKey name, ordered by date\n",
    "    # order set to have the closest image as last element in list\n",
    "    # source: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "    # source: https://developers.google.com/earth-engine/apidocs/ee-join-saveall\n",
    "    join_before = ee.Join.saveAll(\n",
    "        matchesKey = 'before', \n",
    "        ordering = 'system:time_start', \n",
    "        ascending = True)\n",
    "    \n",
    "    join_after = ee.Join.saveAll(\n",
    "        matchesKey = 'after', \n",
    "        ordering = 'system:time_start', \n",
    "        ascending = False)\n",
    "    \n",
    "    # join the cloudfree MODIS 250m collection with itself to get all previous/post images within time-window\n",
    "    # results in image collection where each image has a property that lists all images preceeding/following image within time-window\n",
    "    # source: https://spatialthoughts.com/2021/11/08/temporal-interpolation-gee/\n",
    "    modis_joined_temp = join_before.apply(\n",
    "        primary = modis_cloudFree_withTime, \n",
    "        secondary = modis_cloudFree_withTime, \n",
    "        condition = filter_before)\n",
    "    \n",
    "    modis_joined = join_after.apply(\n",
    "        primary = modis_joined_temp, \n",
    "        secondary = modis_joined_temp, \n",
    "        condition = filter_after)\n",
    "    \n",
    "    # interpolate all images from MODIS 250m image collection\n",
    "    modis_interpolated = ee.ImageCollection(modis_joined.map(interpolateImage))\n",
    "    \n",
    "    \n",
    "    \n",
    "    ###########\n",
    "    ## Look over each step extent entry in the LUT to export corresponding image \n",
    "    ###########\n",
    "    # 1. get dates\n",
    "    # 2. get coordinates \n",
    "    # 3. turn into geometry\n",
    "    # 4. get MODIS image\n",
    "    # 5. reproject \n",
    "    # 6. clip\n",
    "    # 7. calculate NDVI\n",
    "    # 8. export image\n",
    "    \n",
    "    for i in range(len(extents_lut)-1):\n",
    "        # select entry\n",
    "        extent = extents_lut.iloc[i]\n",
    "        \n",
    "        # retrieve extent dates \n",
    "        start_date = extent.loc['start_date']\n",
    "        end_date = extent.loc['end_date']\n",
    "        \n",
    "        start_date_prev_week = extent.loc['start_date_prev_week']\n",
    "        end_date_prev_week = extent.loc['end_date_prev_week']\n",
    "        \n",
    "        # retrieve extent coordinates \n",
    "        # source: https://sparkbyexamples.com/pandas/pandas-get-cell-value-from-dataframe/?utm_content=cmp-true\n",
    "        # source: https://stackoverflow.com/questions/75203044/how-to-create-polygon-from-bbox-data-in-pythonv\n",
    "        coords = [[[extent.loc['xmin'], extent.loc['ymin']],\n",
    "                  [extent.loc['xmin'], extent.loc['ymax']],\n",
    "                  [extent.loc['xmax'], extent.loc['ymax']],\n",
    "                  [extent.loc['xmax'], extent.loc['ymin']]]]\n",
    "    \n",
    "        # create geometry from coordinates\n",
    "        bbox = ee.Geometry.Polygon(coords, proj = 'EPSG:32733', evenOdd = False)\n",
    "        \n",
    "        # retrieve MODIS 250m image for geometry \n",
    "        modis = modis_interpolated \\\n",
    "            .filterDate(start_date, end_date) \\\n",
    "            .filterBounds(enp_geom) \\\n",
    "            .select(['nir', 'red']) \n",
    "        \n",
    "        modis_prev_week = modis_interpolated \\\n",
    "            .filterDate(start_date_prev_week, end_date_prev_week) \\\n",
    "            .filterBounds(enp_geom) \\\n",
    "            .select(['nir', 'red']) \n",
    "        \n",
    "        # reproject image\n",
    "        modis_reproj = modis.map(reprojectModis)\n",
    "        \n",
    "        modis_prev_week_reproj = modis_prev_week.map(reprojectModis)\n",
    "        \n",
    "        # clip image\n",
    "        modis_clipped = modis_reproj.map(clipToAOI(bbox))\n",
    "        \n",
    "        modis_prev_week_clipped = modis_prev_week_reproj.map(clipToAOI(bbox))\n",
    "    \n",
    "        # calculate NDVI \n",
    "        modis_ndvi = modis_clipped.map(addNDVI).select(['NDVI'])\n",
    "    \n",
    "        modis_ndvi_prev_week = modis_prev_week_clipped.map(addNDVI).select(['NDVI'])\n",
    "        \n",
    "        # export MODIS image to local repository \n",
    "        # source: https://github.com/gee-community/geemap/blob/master/examples/notebooks/11_export_image.ipynb\n",
    "        geemap.ee_export_image_collection(modis_ndvi, out_dir = out_dir, region = large_region)\n",
    "        \n",
    "        geemap.ee_export_image_collection(modis_ndvi_prev_week, out_dir = out_dir, region = large_region)\n",
    "    \n",
    "    \n",
    "    \n",
    "    ###########\n",
    "    ## Create and export mean NDVI image for large extent \n",
    "    ###########\n",
    "    # This image will be used as basemap for visualization (no analysis done with it)\n",
    "    # filter dataset to dates\n",
    "    modis_week = modis_interpolated \\\n",
    "        .filterDate(week_start_date, last_date) \\\n",
    "        .filterBounds(enp_geom).select(['nir', 'red']) \n",
    "    \n",
    "    # calculate NDVI \n",
    "    modis_week_ndvi = modis_week.map(addNDVI).select(['NDVI'])\n",
    "    \n",
    "    # create mean NDVI raster\n",
    "    # source: https://developers.google.com/earth-engine/guides/ic_reducing\n",
    "    modis_ndvi_mean = modis_week_ndvi.mean()\n",
    "    \n",
    "    # reproject image\n",
    "    modis_ndvi_mean = modis_ndvi_mean.reproject('EPSG:32733', None, 250)\n",
    "    \n",
    "    # clip image\n",
    "    modis_ndvi_mean = modis_ndvi_mean.clip(large_region)\n",
    "    \n",
    "    # export image\n",
    "    geemap.ee_export_image(modis_ndvi_mean, filename = os.path.join(out_dir, \"mean_ndvi.tif\"), region = large_region, scale = 250)\n",
    "\n",
    "    return print('(DONE) Retrieving cloudmasked and filled MODIS 250m NDVI images corresponding to the movement steps.')\n",
    "    #print('Now extracting covariates...')\n",
    "\n",
    "\n",
    "# read the table with all run settings\n",
    "all_runs = pd.read_csv('data/run_settings_RQ2_rerun.csv', index_col = 0)\n",
    "\n",
    "# iteratte over each entry in the table \n",
    "for i in range(len(all_runs)):\n",
    "    # save the run settings to be read in the function\n",
    "    row = all_runs.iloc[[i]]\n",
    "    row.to_csv('data/single_run_settings.csv', header = False)\n",
    "\n",
    "    # run function for MODIS image retrieval\n",
    "    retrieveMODISImages()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
